# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_useradd'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('login_date_last', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useradd',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAdd',
        ),
    ]
