# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180611_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='short_name',
            field=models.CharField(default='asdasdasd', max_length=50),
        ),
    ]
